// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnvioProductos.API.Models;

public partial class DetalleEnvio
{
    public int Id { get; set; }

    public int EnvioId { get; set; }

    public int ProductoId { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Envio Envio { get; set; }

    public virtual Producto Producto { get; set; }
}