// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnvioProductos.API.Models;

public partial class Envio
{
    public int Id { get; set; }

    public DateTime FechaEnvio { get; set; }

    public string DireccionDestino { get; set; }

    public string Estado { get; set; }

    public int TransportistaId { get; set; }

    public decimal CostoTotal { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<DetalleEnvio> DetalleEnvios { get; set; } = new List<DetalleEnvio>();

    public virtual Transportista Transportista { get; set; }
}