// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EnvioProductos.API.Models;

public partial class EnvioProductosDBContext : DbContext
{
    public EnvioProductosDBContext(DbContextOptions<EnvioProductosDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DetalleEnvio> DetalleEnvios { get; set; }

    public virtual DbSet<Envio> Envios { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<TipoProducto> TipoProductos { get; set; }

    public virtual DbSet<Transportista> Transportistas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DetalleEnvio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DetalleE__3214EC07EE1A90DF");

            entity.HasIndex(e => e.EnvioId, "IX_DetalleEnvios_EnvioId");

            entity.HasIndex(e => e.ProductoId, "IX_DetalleEnvios_ProductoId");

            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Envio).WithMany(p => p.DetalleEnvios)
                .HasForeignKey(d => d.EnvioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleEn__Envio__44FF419A");

            entity.HasOne(d => d.Producto).WithMany(p => p.DetalleEnvios)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DetalleEn__Produ__45F365D3");
        });

        modelBuilder.Entity<Envio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Envios__3214EC07777CDB3D");

            entity.HasIndex(e => e.FechaEnvio, "IX_Envios_FechaEnvio");

            entity.HasIndex(e => e.TransportistaId, "IX_Envios_TransportistaId");

            entity.Property(e => e.CostoTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.DireccionDestino)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.EsActivo).HasDefaultValue(true);
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FechaEnvio).HasColumnType("datetime");

            entity.HasOne(d => d.Transportista).WithMany(p => p.Envios)
                .HasForeignKey(d => d.TransportistaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Envios__Transpor__4222D4EF");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producto__3214EC0782EFB778");

            entity.HasIndex(e => e.TipoProductoId, "IX_Productos_TipoProductoId");

            entity.Property(e => e.EsActivo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Peso).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Precio).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.TipoProducto).WithMany(p => p.Productos)
                .HasForeignKey(d => d.TipoProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Productos__TipoP__3B75D760");
        });

        modelBuilder.Entity<TipoProducto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoProd__3214EC0749D8822F");

            entity.Property(e => e.EsActivo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Transportista>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Transpor__3214EC076CC529A2");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EsActivo).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Telefono).HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    internal List<Envio> GetEnviosConFiltros(string direccion, string estado)
    {
        throw new NotImplementedException();
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}