// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnvioProductos.API.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public decimal Precio { get; set; }

    public decimal Peso { get; set; }

    public int TipoProductoId { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<DetalleEnvio> DetalleEnvios { get; set; } = new List<DetalleEnvio>();

    public virtual TipoProducto TipoProducto { get; set; }
}