// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnvioProductos.API.Models;

public partial class Transportista
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<Envio> Envios { get; set; } = new List<Envio>();
}